services:
  gqrx:
    build: .
    container_name: gqrx
    devices:
      -  /dev/bus/usb:/dev/bus/usb
    volumes:
      - ${HOME}/.config/gqrx:/root/.config/gqrx
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/${UID}/pulse:/run/pulse:ro
      - /var/lib/dbus:/var/lib/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      - DISPLAY=unix$DISPLAY
      - USER_UID=${UID}
      - USER_GID=${GID}
    network_mode: "host"
    entrypoint: ["/start-gqrx.sh"]
