services:
  gqrx:
    build: .
    container_name: gqrx
    devices:
      -  /dev/bus/usb:/dev/bus/usb
    volumes:
      - ${HOME}/.config/gqrx:/root/.config/gqrx
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/${UID}/pulse:/run/pulse:ro
      - /var/lib/dbus:/var/lib/dbus
    environment:
      - DISPLAY=unix$DISPLAY
      - USER_UID=1001
      - USER_GID=1001
    network_mode: "host"
    entrypoint: ["/usr/local/bin/gqrx"]
